using OuterloopLabApi.Data;
using OuterloopLabApi.Exceptions;
using OuterloopLabApi.Models;

namespace OuterloopLabApi.Services;

public sealed class CurrencyConversionService
{
    private readonly ICurrencyRateProvider _rateProvider;
    private readonly ICosmosConversionAuditRepository _auditRepository;

    public CurrencyConversionService(ICurrencyRateProvider rateProvider, ICosmosConversionAuditRepository auditRepository)
    {
        _rateProvider = rateProvider;
        _auditRepository = auditRepository;
    }

    public async Task<ConversionResult> ConvertAndPersistAsync(CreateConversionRequest request, CancellationToken cancellationToken)
    {
        var from = request.FromCurrency.Trim().ToUpperInvariant();
        var to = request.ToCurrency.Trim().ToUpperInvariant();

        if (!IsValidCurrencyCode(from) || !IsValidCurrencyCode(to) || from.Length != 3 || to.Length != 3)
        {
            throw new ArgumentException("Currency codes must be three-letter values.");
        }

        if (request.Amount <= 0)
        {
            throw new ArgumentException("Amount must be a positive value.");
        }

        var provider = await _rateProvider.GetRateAsync(from, to, cancellationToken);

        // Preserve sub-second audit reconstruction: executedAtUtc is generated by this backend server.
        var executedAtUtc = DateTime.UtcNow;

        var converted = request.Amount * provider.Rate;

        // Display/persist rounding: 2 decimals.
        var roundedConverted = decimal.Round(converted, 2, MidpointRounding.AwayFromZero);
        var roundedRate = decimal.Round(provider.Rate, 6, MidpointRounding.AwayFromZero);

        var conversionId = Guid.NewGuid().ToString("n");

        var record = new ConversionAuditRecord
        {
            Id = conversionId,
            ConversionId = conversionId,
            FromCurrency = provider.FromCurrency,
            ToCurrency = provider.ToCurrency,
            Amount = request.Amount,
            Rate = roundedRate,
            ConvertedAmount = roundedConverted,
            ProviderDateMarker = provider.ProviderDateMarker,
            ExecutedAtUtc = executedAtUtc,
            ProviderRawJson = provider.RawJson,
        };

        var saved = await _auditRepository.UpsertAsync(record, cancellationToken);

        return new ConversionResult(
            ConversionId: saved.ConversionId,
            FromCurrency: saved.FromCurrency,
            ToCurrency: saved.ToCurrency,
            Amount: saved.Amount,
            Rate: saved.Rate,
            ConvertedAmount: saved.ConvertedAmount,
            ProviderDateMarker: saved.ProviderDateMarker,
            ExecutedAtUtc: saved.ExecutedAtUtc);
    }

    public async Task<ConversionResult> GetByIdAsync(string conversionId, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(conversionId))
        {
            throw new ArgumentException("conversionId is required");
        }

        var record = await _auditRepository.GetByIdAsync(conversionId.Trim(), cancellationToken);
        if (record is null)
        {
            throw new ConversionNotFoundException(conversionId);
        }

        return new ConversionResult(
            ConversionId: record.ConversionId,
            FromCurrency: record.FromCurrency,
            ToCurrency: record.ToCurrency,
            Amount: record.Amount,
            Rate: record.Rate,
            ConvertedAmount: record.ConvertedAmount,
            ProviderDateMarker: record.ProviderDateMarker,
            ExecutedAtUtc: record.ExecutedAtUtc);
    }

    private static bool IsValidCurrencyCode(string code)
    {
        return code.Length == 3 && code.All(char.IsLetter);
    }
}
